### ISSUE TITLE
calculate mortgage denial rate for JPMC Equity feature

### ISSUE THREAD

**Issue by maggiesu0725** [NeighborhoodInfoDC/HMDA#12]

**Comment by maggiesu0725** [comment]
@rpitingolo  two questions for you. 1. This dataset seems to include tracts outside of DC?  Is it address of where they applied the loan? Should I just exclude them? 2. It is unclear what variable we should use as the denominator for denial rate, since this dataset is action based instead of record based. Open to suggestions, but one proxy we can use is Loan originated from last year, based on the assumption that last year's record will likely to show up this year. 

cc @ptatian @lhendey

**Comment by maggiesu0725** [comment]
Or a several year average

**Comment by rpitingolo** [comment]
@maggiesu0725 Yes, the dataset is for the whole region, so just keep the records where the tract is in DC (you can substring the first 2 digits of geo2010 and then keep if the new variable = 11. 

Here is the Fed's definition for how to define the denial rate: Denial rates are calculated as the number of denied loan applications divided by the total number of applications, excluding withdrawn applications and application files closed for incompleteness.

I'm not sure I understand your proposal for using a proxy.

**Comment by maggiesu0725** [comment]
@rpitingolo thanks, make sense
