### ISSUE TITLE
HMDA web update

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/HMDA#26]

**Comment by rpitingolo** [comment]
In order to export for the data explorer the HMDA summary files need to have a denominator for the "loans per 1,000 housing units" indicators. The previous HMDA summary files all used the same Census 2000 housing units count for years 1997-2008. The p09 summary files don't currently have a denominator. I think we have two options.

1) use Census 2010 counts as the denominator for 2010 and later years, keep Census 2000 for 2009 and earlier. 
2) use the Num_units summary files from the Realprop library to assign unit counts for each individual year (I think units_sf_condo_yyyy is the correct indicator for this).

My vote is for option 2 because it gives us more accurate numbers but maybe I am missing something? The obvious disadvantage to option 2 is that we are changing data that is previously on the explorer for the 2008 and earlier years. 

@ptatian @lhendey can you please vote on which option you think is best?

**Comment by lhendey** [comment]
@rpitingolo @ptatian 

 #2 only applies to DC. we should be producing summary files for the region. (it appears we don't currently have HMDA for the region on the data explorer?) 

i would think we'd want a consistent approach across jurisdictions. 
what about interpolate between census 2010 and 2000 to assign annual values between 2000 and 2010 and use 2010 after? (not ideal but probably not worse than the ACS counts at the tract level?

**Comment by rpitingolo** [comment]
@lhendey ah, you are right. I don't know why that slipped my mind. Interpolating is not ideal but better than the alternatives.

**Comment by rpitingolo** [comment]
@lhendey @ptatian so to confirm, I am going to use 2000 for years 1997-2000, then interpolate 2001-2009, and then use 2010 for all years after that.

**Comment by rpitingolo** [comment]
No batch submit since it's part of the web update.
