### ISSUE TITLE
Run HMDA tract summary

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/HMDA#9]

**Comment by rpitingolo** [comment]
@ptatian Looking ahead to the next step in this process, it looks like there's going to be some issues to resolve. 

Looking at the program HMDA_sum_tr00.sas, it seems like this program is designed to take the loan-level data and summarize it to the tract-level and then create a time-series file; but I can't run it as-is because it's calling a lot of datasets that appear to be in .zip files on L for some reason? Is there any reason I shouldn't just unzip them?

Starting in 2012 the tract ID switches from geo2000 to geo2010. Since this is summarizing at the tract-level, I assume we we need to have two separate datasets (one for 2011 and earlier, one for 2012 and later). Or should we re-weight all the data into geo2010 tracts? In order to run HMDA_sum_all.sas we need to specify the tract year. Please let me know what you think. Thanks.

**Comment by ptatian** [comment]
Hi @rpitingolo. I think the zipping was probably a space issue. If that's no longer a concern then it's fine to unzip the files. 

Yes, you are right the 2000 and 2010 tracts will need to be summarized separately. My suggestion would be create separate summary files for the pre-2012 and more recent data. It will mean ending up with two sets of summary data sets (like with NCDB), but I don't think that's a problem. 

Alternatively, you could try to figure out a way to process all the years together, but that's probably more trouble than it is worth. 

Let me know how that sounds. Thanks.

**Comment by rpitingolo** [comment]
@ptatian thanks. I'll try to unzip them and see if I can get the program running.

Having 2 summary files seems like a fine solution to me. No need to overcomplicate it.

**Comment by rpitingolo** [comment]
@ptatian can you please remind me the syntax for only keeping observations where the geo variable has a  valid format? I am having a hard time finding it even though I know I've used it in the past.

**Comment by ptatian** [comment]
The basic syntax is `if put( geo, $geovfmt. ) ~= '';`

Where you would replace _geo_ with the name of the geographic var and _$geovfmt_ with the name of the geo validation format. You can hard code the format names or use this macro code to generate them from the geo name.

```
  %macro keepvalidgeo( geo );

    %local geovfmt;

    %let geo = %upcase( &geo );
    %let geovfmt = %sysfunc( putc( &geo, $geovfmt. ) );

    if put( &geo., &geovfmt ) = '';

  %mend keepvalidgeo;
```

**Comment by rpitingolo** [comment]
@ptatian thanks Peter. FYI I am still working on this. The by race macro is not working properly so I am troubleshooting it now.

**Comment by ptatian** [comment]
Thanks @rpitingolo for keeping me updated.

**Comment by rpitingolo** [comment]
L:\Libraries\HMDA\Prog\HMDA_sum_P09.log

@ptatian FYI there are some errors in this log. They are generated from the %Finalize_data_set() macro inside the %Create_summary_from_tracts() macro. There is already an issue (General 67)  to correct this and it doesn't impact the creation of the data, so I'm going to close this issue anyway.
